// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uavranmoljgzoaeywjhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhdnJhbm1vbGpnem9hZXl3amh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzU1ODMsImV4cCI6MjA3MTIxMTU4M30.WWN5ytRy0pxChcj211w7eqMPGNE37nZbXsRyaCKlFjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});